server:
  port: 9081
  session:
    timeout: 50
    cookie:
      http-only: true
      #domain: liyuchang.cn
      #secure: true #true不能https访问才会设置cookie
      #max-age: 86400 #浏览器端JSESSIONID的cookie过期时间 

spring:
  application:
    name: spring-security-samples-boot-helloworld-9081
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

security:
  ignored: /css/**, /index
  #user:
  #  name: user
  #  password: pwd
  #  role: ROLE,USER

logging:
  file: ../log/spring-security-samples-boot-helloworld/log.log
  level:
    root: INFO
    org.springframework: INFO