server:
  port: 8081

logging:
  file: ../log/spring-security-samples-boot-helloworld/log.log
  level:
    root: INFO
    org.springframework: INFO
spring:
  thymeleaf:
    cache: false

security:
  ignored: /css/**, /index
  #user:
  #  name: user
  #  password: pwd
  #  role: ROLE,USER