server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework: INFO
spring:
  thymeleaf:
    cache: false

security:
  ignored: /css/**, /index
  #user:
  #  name: user
  #  password: pwd
  #  role: ROLE,USER